
{{#ROCKER_DEV_WORKFLOW}}
COPY scripts/install_verse.sh /rocker_scripts/install_verse.sh
COPY scripts/install_texlive.sh /rocker_scripts/install_texlive.sh
{{/ROCKER_DEV_WORKFLOW}}

ENV CTAN_REPO=${CTAN_REPO:-http://mirror.ctan.org/systems/texlive/tlnet}
ENV PATH=/usr/local/texlive/bin/x86_64-linux:$PATH
ENV PATH=/opt/texlive/bin/x86_64-linux:$PATH
RUN /rocker_scripts/install_verse.sh
RUN /rocker_scripts/install_texlive.sh


