FROM rockerdev/r-ver:4.0.0

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ENV S6_VERSION=v1.21.7.0 \ 
    SHINY_SERVER_VERSION=latest \ 
    PANDOC_VERSION=default


RUN /rocker_scripts/install_shiny_server.sh

EXPOSE 3838

CMD /init



