FROM rockerdev/geospatial:devel

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"


ENV WORKON_HOME=/opt/venv

## A default python venv, e.g. for binder etc.
ENV PYTHON_VENV_PATH=${WORKON_HOME}/reticulate 


ENV RETICULATE_AUTOCONFIGURE=0

## Add this venv to path (FIXME should use symlinks for pip, python, virtualenv in script instead?
ENV PATH=${PYTHON_VENV_PATH}/bin:${PATH}

RUN . /rocker_scripts/install_python.sh



ENV NB_USER rstudio
ENV NB_UID 1000
ENV HOME /home/${NB_USER}

# The `rsession` binary that is called by nbrsessionproxy to start R doesn't seem to start
# without this being explicitly set 
ENV LD_LIBRARY_PATH ${R_HOME}/lib


RUN /rocker_scripts/install_binder.sh

WORKDIR /home/{NB_USER}
USER ${NB_USER}

EXPOSE 8888
CMD jupyter notebook --ip 0.0.0.0
## If extending this image, remember to switch back to USER root to apt-get



