FROM rockerdev/r-ver:3.6.3

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"
ENV S6_VERSION=
ENV SHINY_SERVER_VERSION=

RUN /rocker_scripts/install_shiny_server.sh
