FROM rockerdev/r-ver-gpu:4.0.0-cuda10.2

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ENV S6_VERSION=v1.21.7.0 \ 
    RSTUDIO_VERSION=latest \ 
    PANDOC_VERSION=default \ 
    WORKON_HOME=/opt/venv \ 
    PYTHON_VENV_PATH=${WORKON_HOME}/reticulate \ 
    RETICULATE_AUTOCONFIGURE=0 \ 
    PATH=${PYTHON_VENV_PATH}/bin:${PATH} \ 
    TENSORFLOW_VERSION=gpu \ 
    KERAS_VERSION=default


RUN /rocker_scripts/install_rstudio.sh
RUN /rocker_scripts/install_pandoc.sh
RUN /rocker_scripts/install_tidyverse.sh
RUN /rocker_scripts/install_tensorflow.sh

EXPOSE 8787

CMD /init



