FROM rockerdev/tidyverse:4.0.0

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ENV WORKON_HOME=/opt/venv \ 
    PYTHON_VENV_PATH=${WORKON_HOME}/reticulate \ 
    RETICULATE_AUTOCONFIGURE=0 \ 
    PATH=${PYTHON_VENV_PATH}/bin:${PATH} \ 
    TENSORFLOW_VERSION=cpu \ 
    KERAS_VERSION=default


RUN /rocker_scripts/install_tensorflow.sh





