
FROM ubuntu:20.04

ENV R_VERSION=4.0.0
ENV TERM=xterm
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV R_HOME=/usr/local/lib/R
ENV CRAN=https://cran.r-project.org

COPY scripts /rocker_scripts

RUN /rocker_scripts/install_R.sh


CMD R



