# syntax = docker/dockerfile:1.0-experimental
FROM ubuntu:20.04

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ARG BUILDKIT_CACHE=1
ARG R_MAKEVARS_SITE=/rocker_scripts/Makevars.ccache
ARG APT_CONFIG=/rocker_scripts/apt-config

ENV R_VERSION=devel
ENV TERM=xterm
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV R_HOME=/usr/local/lib/R
ENV CRAN=https://cran.r-project.org

COPY scripts /rocker_scripts

RUN --mount=type=cache,id=rocker_ccache,target=/root/.ccache --mount=type=cache,id=rocker_cache_apt,target=/var/cache/apt --mount=type=cache,id=rocker_lib_apt,target=/var/lib/apt /rocker_scripts/install_R.sh


CMD R



