FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

COPY scripts /rocker_scripts

# Set system environmetnal variables
ENV TERM=xterm
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV UBUNTU_VERSION=bionic
ENV CRAN_LINUX_VERSION=

# Set up and install R
ENV R_HOME=/usr/lib/R
ENV R_VERSION=4.0.0

ENV CRAN=https://cran.rstudio.com


RUN /rocker_scripts/install_R.sh
## Use Configure CUDA for R, use NVidia libs for BLAS
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=$PATH:$CUDA_HOME/bin
ENV LD_LIBRARY_PATH=$CUDA_HOME/lib64/libnvblas.so:$LD_LIBRARY_PATH:$CUDA_HOME/lib64:$CUDA_HOME/extras/CUPTI/lib64
ENV NVBLAS_CONFIG_FILE=/etc/nvblas.conf
RUN . /rocker_scripts/config_R_cuda.sh



# Install RStudio
ENV S6_VERSION=v1.21.7.0
ENV RSTUDIO_VERSION=


RUN /rocker_scripts/install_rstudio.sh


RUN /rocker_scripts/install_pandoc.sh


RUN /rocker_scripts/install_s6init.sh
RUN /rocker_scripts/default_user.sh

RUN cp /rocker_scripts/userconf.sh /etc/cont-init.d/userconf



RUN /rocker_scripts/install_tidyverse.sh




ENV CTAN_REPO=${CTAN_REPO:-http://mirror.ctan.org/systems/texlive/tlnet}
ENV PATH=/usr/local/texlive/bin/x86_64-linux:$PATH
ENV PATH=/opt/texlive/bin/x86_64-linux:$PATH
RUN /rocker_scripts/install_verse.sh
RUN /rocker_scripts/install_texlive.sh


RUN /rocker_scripts/install_geospatial.sh




ENV WORKON_HOME=/opt/venv
ENV PYTHON_VENV_PATH=${WORKON_HOME}/reticulate 

#ENV RETICULATE_PYTHON_ENV=$PYTHON_VENV_PATH
ENV PATH=${PYTHON_VENV_PATH}/bin:${PATH}
RUN . /rocker_scripts/install_python.sh

ENV TENSORFLOW_VERSION=gpu
RUN . /rocker_scripts/install_tensorflow.sh


CMD "/init"
EXPOSE 8787
