FROM ubuntu:20.04

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ENV R_VERSION=devel \ 
    TERM=xterm \ 
    LC_ALL=en_US.UTF-8 \ 
    LANG=en_US.UTF-8 \ 
    R_HOME=/usr/local/lib/R \ 
    CRAN=https://cran.r-project.org

COPY scripts /rocker_scripts

RUN /rocker_scripts/install_R.sh


CMD R



