FROM rocker/verse:4.0.2

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ENV PROJ_VERSION=7.1.0
ENV GDAL_VERSION=3.1.2
ENV GEOS_VERSION=3.8.0


RUN /rocker_scripts/install_geospatial_unstable.sh





