FROM nvidia/cuda:10.0-cudnn7-devel

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

COPY scripts /rocker_scripts

# Set system environmetnal variables
ENV TERM=xterm
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV UBUNTU_VERSION=bionic

# Set up and install R
ENV R_HOME=/usr/lib/R
ENV R_VERSION=3.6.3

ENV CRAN=https://cran.rstudio.com

RUN /rocker_scripts/install_R.sh
## Use Configure CUDA for R, use NVidia libs for BLAS
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=$PATH:$CUDA_HOME/bin
ENV LD_LIBRARY_PATH=$CUDA_HOME/lib64/libnvblas.so:$LD_LIBRARY_PATH:$CUDA_HOME/lib64:$CUDA_HOME/extras/CUPTI/lib64
ENV NVBLAS_CONFIG_FILE=/etc/nvblas.conf
RUN . /rocker_scripts/config_R_cuda.sh



# Install RStudio
ENV S6_VERSION=
ENV RSTUDIO_VERSION=


RUN /rocker_scripts/install_rstudio.sh


RUN /rocker_scripts/install_pandoc.sh


RUN /rocker_scripts/install_s6init.sh
RUN cp /rocker_scripts/userconf.sh /etc/cont-init.d/userconf




ENV WORKON_HOME=/opt/venv
ENV PYTHON_VENV_PATH=${WORKON_HOME}/reticulate 

#ENV RETICULATE_PYTHON_ENV=$PYTHON_VENV_PATH
ENV PATH=${PYTHON_VENV_PATH}/bin:${PATH}
RUN . /rocker_scripts/install_python.sh

ENV TENSORFLOW_VERSION=gpu
RUN . /rocker_scripts/install_tensorflow.sh


