FROM rocker/geospatial:3.6.2

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"
ENV PYTHON_VENV_PATH=/opt/venv 
ENV RETICULATE_PYTHON_ENV=$PYTHON_VENV_PATH
ENV PATH=${PYTHON_VENV_PATH}/bin:${PATH}
COPY scripts/install_python.sh /rocker_scripts/install_python.sh
RUN . /rocker_scripts/install_python.sh
COPY scripts/install_tensorflow.sh /rocker_scripts/install_tensorflow.sh
ENV TENSORFLOW_VERSION=default
RUN . /rocker_scripts/install_tensorflow.sh


