FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

COPY scripts /rocker_scripts

# Set system environmetnal variables
ENV TERM=xterm
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV UBUNTU_VERSION=bionic
ENV CRAN=https://cran.r-project.org

# Set up and install R
ENV R_HOME=/usr/local/lib/R
ENV R_VERSION=4.0.0


RUN /rocker_scripts/install_R_source.sh




ENV CTAN_REPO=${CTAN_REPO:-http://mirror.ctan.org/systems/texlive/tlnet}
ENV PATH=/usr/local/texlive/bin/x86_64-linux:$PATH
ENV PATH=/opt/texlive/bin/x86_64-linux:$PATH
RUN /rocker_scripts/install_verse.sh
RUN /rocker_scripts/install_texlive.sh


