FROM rocker/tidyverse:3.6.3-gpu

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"


ENV CTAN_REPO=${CTAN_REPO:-https://www.texlive.info/tlnet-archive/2019/02/27/tlnet}
ENV PATH=/usr/local/texlive/bin/x86_64-linux:$PATH
ENV PATH=/opt/texlive/bin/x86_64-linux:$PATH
RUN /rocker_scripts/install_verse.sh


