FROM rockerdev/verse:4.0.0-ubuntu18.04

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

ENV UBUNTUGIS_VERSION=unstable


RUN /rocker_scripts/add_ubuntugis.sh
RUN /rocker_scripts/install_geospatial.sh





