FROM rocker/tidyverse:3.6.2

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"

COPY scripts/install_verse.sh /rocker_scripts/install_verse.sh
COPY scripts/install_texlive.sh /rocker_scripts/install_texlive.sh

ENV PATH=/usr/local/texlive/bin/x86_64-linux:$PATH
ENV PATH=/opt/texlive/bin/x86_64-linux:$PATH
RUN /rocker_scripts/install_verse.sh


