FROM rockerdev/geospatial:3.6.3

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/rocker-org/rocker-versioned" \
      org.label-schema.vendor="Rocker Project" \
      maintainer="Carl Boettiger <cboettig@ropensci.org>"


ENV WORKON_HOME=/opt/venv
ENV PYTHON_VENV_PATH=${WORKON_HOME}/reticulate 

#ENV RETICULATE_PYTHON_ENV=$PYTHON_VENV_PATH
ENV PATH=${PYTHON_VENV_PATH}/bin:${PATH}
RUN . /rocker_scripts/install_python.sh

ENV TENSORFLOW_VERSION=gpu
RUN . /rocker_scripts/install_tensorflow.sh


