version: '3'
services:
  r-ver-4.0.5-cuda10.1:
    image: rocker/r-ver:4.0.5-cuda10.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_r-ver_4.0.5-cuda10.1
  ml-4.0.5-cuda10.1:
    image: rocker/ml:4.0.5-cuda10.1
    depends_on:
    - r-ver-4.0.5-cuda10.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml_4.0.5-cuda10.1
  ml-verse-4.0.5-cuda10.1:
    image: rocker/ml-verse:4.0.5-cuda10.1
    depends_on:
    - ml-4.0.5-cuda10.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml-verse_4.0.5-cuda10.1
  ml-4.0.5:
    image: rocker/ml:4.0.5
    depends_on:
    - ml-verse-4.0.5-cuda10.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml_4.0.5
  ml-verse-4.0.5:
    image: rocker/ml-verse:4.0.5
    depends_on:
    - ml-4.0.5
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml-verse_4.0.5
