FROM rocker/ml:cuda11.1

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

RUN apt-get update && apt-get install -y --no-install-recommends \
  cuda-samples-11-1 \
  python3-dev \
  python3-pip

# install tensorflow 1.15.5
RUN pip install nvidia-pyindex
RUN pip install nvidia-tensorflow[horovod]

WORKDIR /usr/local/cuda-11.1/samples
RUN make

COPY nvblas.R /
COPY test-gpu.sh /
COPY examples_tf.R /

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
