FROM rocker/ml:4.0.5-cuda10.1

RUN apt-get update && apt-get install -y --no-install-recommends \
  cuda-samples-10-0 \
  python3-dev \
  python3-pip

# WORKDIR /usr/local/cuda-10.0/samples
# RUN make

COPY ./test-gpu.sh /test-gpu.sh
RUN chmod +x /test-gpu.sh

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
