FROM rocker/ml:4.0.5-cuda11.1

RUN apt-get update && apt-get install -y --no-install-recommends \
  software-properties-common \
  cuda-samples-11-1 \
  python3-dev \
  python3-pip

WORKDIR /root
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
RUN mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
RUN add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
RUN apt-get update
RUN wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
RUN apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
RUN apt-get update

RUN apt-get update && apt-get install -y --no-install-recommends \
  libcudnn8=8.0.4.30-1+cuda11.0  \
  libcudnn8-dev=8.0.4.30-1+cuda11.0

RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/extras/CUPTI/samples

RUN pip install tensorflow

RUN apt-get install -y --no-install-recommends libnvinfer7=7.1.3-1+cuda11.0 \
    libnvinfer-dev=7.1.3-1+cuda11.0 \
    libnvinfer-plugin7=7.1.3-1+cuda11.0

# WORKDIR /usr/local/cuda-11.1/samples
# RUN make

COPY ./test-gpu.sh /test-gpu.sh
RUN chmod +x /test-gpu.sh

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
