FROM rocker/ml:4.0.5-cuda11.1

RUN apt-get update && apt-get install -y --no-install-recommends \
  cuda-samples-11-1 \
  python3-dev \
  python3-pip

RUN pip install --upgrade tensorflow

WORKDIR /usr/local/cuda-11.1/samples
RUN make

COPY ./test-gpu.sh /test-gpu.sh
RUN chmod +x /test-gpu.sh

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
